config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :trips do
    get 'join', on: :member

    member do
      patch 'accept_request'
      delete 'reject_request'
      get 'manage_requests'
    end
  end

  delete 'trips/:id', to: 'trips#destroy'
  get 'my_trips', to: 'trips#my_trips'
  
  resources :users
  root to: 'pages#home'
  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates  :trip_type, inclusion: { in: ['Solicitada', 'Oferecida'], message: "Deve ser uma viagem solicita ou oferecida" }
  
  validates :departure_location, :arrival_location, :departure_date, :arrival_date,
            :departure_time, :arrival_time, :trip_type, presence: true

  belongs_to :user
  serialize :participants, Array
  serialize :requested_participants, Array

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["arrival_date", "arrival_location", "arrival_time", "created_at", "departure_date", "departure_location", "departure_time", "id", "trip_type", "updated_at", "user_id"]
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create ]

  # GET /trips or /trips.json
  def index
    @q = Trip.ransack(params[:q])
    @trips = @q.result 
  end

  # GET /trips/1 or /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = current_user.trips.build
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips or /trips.json
  def create
    @trip = current_user.trips.build(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def join
    @trip = Trip.find(params[:id])
  
    if current_user == @trip.user
      redirect_to trips_path, notice: "You cannot join your own trip."
    elsif @trip.participants.include?(current_user.name)
      redirect_to trips_path, notice: "You are already a participant of this trip."
    elsif @trip.requested_participants.include?(current_user.name)
      redirect_to trips_path, notice: "You have already requested to join this trip."
    else
      @trip.requested_participants << current_user.name
      @trip.save
      redirect_to trips_path, notice: "You have requested to join this trip."
    end
  end

  def manage_requests
    @trip = Trip.find(params[:id])
    @requested_participants = @trip.requested_participants
  end

  def accept_request
    @trip = Trip.find(params[:id])
    participant = params[:participant]
  
    if @trip.user == current_user && @trip.requested_participants.include?(participant)
      @trip.participants << participant
      @trip.requested_participants.delete(participant)
      @trip.save
  
      notice_message = "#{participant} has been accepted as a participant."
  
      if @trip.requested_participants.any?
        redirect_to manage_requests_trip_path(@trip), notice: notice_message
      else
        redirect_to trip_path(@trip), notice: notice_message
      end
    else
      redirect_to manage_requests_trip_path(@trip), alert: "Invalid request."
    end
  end
  
  def reject_request
    @trip = Trip.find(params[:id])
    participant = params[:participant]
  
    if @trip.user == current_user && @trip.requested_participants.include?(participant)
      @trip.requested_participants.delete(participant)
      @trip.save
  
      notice_message = "#{participant} has been rejected as a participant."
  
      if @trip.requested_participants.any?
        redirect_to manage_requests_trip_path(@trip), notice: notice_message
      else
        redirect_to trip_path(@trip), notice: notice_message
      end
    else
      redirect_to manage_requests_trip_path(@trip), alert: "Invalid request."
    end
  end

  def my_trips
    @my_trips = current_user.trips
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(:departure_location, :arrival_location, :departure_date, :arrival_date, :departure_time, :arrival_time, :trip_type, :user_id)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<% content_for :body_class, 'body' %>

<%= form_with(model: trip) do |form| %>
  <% if trip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trip.errors.count, "erro") %> impediu que esta viagem fosse salva:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :departure_location, "Local de Partida:", style: "display: block" %>
    <%= form.text_field :departure_location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :arrival_location, "Local de Chegada:", style: "display: block" %>
    <%= form.text_field :arrival_location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :departure_date, "Data de Partida:", style: "display: block" %>
    <%= form.date_field :departure_date, class: "form-control smaller-input" %>
  </div>

  <div class="form-group">
    <%= form.label :arrival_date, "Data de Chegada:", style: "display: block" %>
    <%= form.date_field :arrival_date, class: "form-control smaller-input" %>
  </div>

  <div class="form-group">
    <%= form.label :departure_time, "Hora de Partida:", style: "display: block" %>
    <%= form.time_field :departure_time, class: "form-control smaller-input"  %>
  </div>

  <div class="form-group">
    <%= form.label :arrival_time, "Hora de Chegada:", style: "display: block" %>
    <%= form.time_field :arrival_time, class: "form-control smaller-input"  %>
  </div>

  <div class="form-group">
    <%= form.label "Tipo de Viagem:", style: "display: block" %>
    <%= form.select :trip_type, [['Solicitada', 'Solicitada'], ['Oferecida', 'Oferecida']], { include_blank: false }, class: "form-control smaller-input"  %>
  </div>

  <div class="form-group">
    <%= form.submit "Enviar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<style>
  #<%= dom_id(trip) %> {
    border: 1px solid #ccc;
    padding: 15px;
    margin-bottom: 15px;
    border-radius: 5px;
    background-color: rgba(255, 255, 255, 0.8);
  }

  p {
    margin: 5px 0;
  }

  strong {
    font-weight: bold;
  }
</style>
<% content_for :body_class, 'body' %>

<div id="<%= dom_id(trip) %>">
  <p>
    <strong>Local de Partida:</strong>
    <%= trip.departure_location %>
  </p>

  <p>
    <strong>Local de Chegada:</strong>
    <%= trip.arrival_location %>
  </p>

  <p>
    <strong>Data de Partida:</strong>
    <%= trip.departure_date %>
  </p>

  <p>
    <strong>Data de Chegada:</strong>
    <%= trip.arrival_date %>
  </p>

  <p>
    <strong>Hora de Partida:</strong>
    <%= trip.departure_time.strftime('%H:%M:%S %Z') %>
  </p>

  <p>
    <strong>Hora de Chegada:</strong>
    <%= trip.arrival_time.strftime('%H:%M:%S %Z') %>
  </p>

  <p>
    <strong>Tipo de Viagem:</strong>
    <%= trip.trip_type %>
  </p>

  <p>
    <strong>Usuário:</strong>
    <%= trip.user.name %>
  </p>

  <% if trip.requested_participants.any? %>
    <p>
      <strong>Solicitações:</strong>
      <%= trip.requested_participants.join(', ') %> 
    </p>
  <% end %>

  <% if trip.trip_type == 'Oferecida' %>
    <p>
      <strong>Participantes:</strong>
      <%= trip.participants.join(', ') %>
    </p>
  <% else %>
    <p>
      <strong>Motoristas:</strong>
      <%= trip.participants.join(', ') %>
    </p>
  <% end %>
</div>

app/views/trips/edit.html.erb
<h1>Editar Frete</h1>

<%= render "form", trip: @trip %>

<br>


<div>
  <% if current_user && @trip.user.eql?(current_user) %>
    <% if @trip.requested_participants.any? %>
      <%= link_to "Manage Requests", manage_requests_trip_path(@trip), class: "btn btn-default"%> 
    <% end %>
  <% end %>
  <%= link_to "Ver frete", @trip, class: "btn btn-default" %> 
  <%= link_to "Voltar", trips_path, class: 'btn btn-default' %>
</div>

app/views/trips/index.html.erb
<style>
  #trips {
    table-layout: auto;
    width: 90%;
    margin: auto;
    border-collapse: collapse;
  }

  #trips th,
  #trips td {
    text-align: center;
    padding: 10px;
    border: 1px solid #ccc;
  }

  #trips th {
    background-color: #f2f2f2;
  }


  #trips tbody tr:nth-child(odd) {
    background-color: #e0e0e0;
  }

  #trips tbody tr:nth-child(even) {
    background-color: #f9f9f9;
  }

  .search-container {
    width: 100%;
    margin: auto;
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    margin-bottom: 20px;
    margin-right: 10px;
  }

  .search-box {
    width: 100%;
    padding: 10px;
    background-color: #f2f2f2;
    border: 1px solid #ccc;
    border-radius: 10px;
    margin-right: 10px;
  }

  .search-box label,
  .search-box input[type="text"],
  .search-box .actions {
    width: 100%;
    margin-bottom: 10px;
  }

  /* Clear floating elements after the search box and the grid */
  .clear {
    clear: both;
  }


</style>

<% content_for :body_class, 'body' %>

<p style="color: green"><%= notice %></p>
<h1>Fretes</h1>
<div class="search-container">
  <div class="search-box">
    <%= search_form_for @q do |f| %> 
      <%= f.label :departure_location, "Local de Partida:" %>
      <%= f.text_field :departure_location_cont, class: 'form-control' %>

      <%= f.label :arrival_location, "Local de Chegada:" %>
      <%= f.text_field :arrival_location_cont, class: 'form-control' %>

      <%= f.label :departure_date, "Data de Partida:" %>
      <%= f.text_field :departure_date_cont, class: 'form-control', placeholder: 'dd/mm/aaaa' %>

      <%= f.label :arrival_date, "Data de Chegada:" %>
      <%= f.text_field :arrival_date_cont, class: 'form-control', placeholder: 'dd/mm/aaaa' %>

      <%= f.label :trip_type, "Tipo de Viagem:" %>
      <%= f.text_field :trip_type_cont, class: 'form-control' %>
      <div class="actions">
        <%= f.submit "Buscar", class: 'btn btn-primary' %>
        <%= link_to "Limpar", request.path, class: "btn btn-default" %>
      </div>

      <%= link_to "Novo frete", new_trip_path, class: 'btn btn-default btn-gray' %>
    <% end %>
  </div>

<body>
  <table id="trips">
    <thead>
      <tr>
        <th>Local de Partida</th>
        <th>Local de Chegada</th>
        <th>Data de Partida</th>
        <th>Data de Chegada</th>
        <th>Hora de Partida</th>
        <th>Hora de Chegada</th>
        <th>Tipo de Viagem</th>
        <th>Participantes</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @trips.each do |trip| %>
        <tr>
          <td><%= trip.departure_location %></td>
          <td><%= trip.arrival_location %></td>
          <td><%= trip.departure_date.strftime('%d/%m/%Y') %></td>
          <td><%= trip.arrival_date.strftime('%d/%m/%Y') %></td>
          <td><%= trip.departure_time.strftime('%H:%M:%S %Z') %></td>
          <td><%= trip.arrival_time.strftime('%H:%M:%S %Z') %></td>
          <td><%= trip.trip_type %></td>
          <td>
          <% trip.participants.each do |participant| %>
            <%= participant %><br>
          <% end %>
          </td>
          <td>
            <%= link_to "Detalhes", trip, class: "btn btn-primary", style: "margin-bottom: 5px;"%>
            <% if current_user && !trip.user.eql?(current_user) %>
              <% if trip.trip_type == 'Oferecida'%>
                <%= link_to "Solicitar frete", join_trip_path(trip), method: :post, class: "btn btn-primary"%>
              <% else %>
                <%= link_to "Oferecer frete", join_trip_path(trip), method: :post, class: "btn btn-primary" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body> 
</div>

app/views/trips/manage_requests.html.erb
<% content_for :body_class, 'body' %>

<div class="panel">
  <h1 style="font-size: 21px;">Gerencie suas solicitações:</h1>
  <div>
    <ul>
      <% @requested_participants.each do |participant| %>
        <li>
          <%= participant %>
          <%= button_to "Aceitar", accept_request_trip_path(@trip, participant: participant), method: :patch, class: "btn btn-success", style: "float: left; margin-right: 5px;" %>
          <%= button_to "Rejeitar", reject_request_trip_path(@trip, participant: participant), method: :delete, class: "btn btn-danger", style: "float: left; margin-right: 5px;" %>
          <div style="clear: both;"></div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/trips/my_trips.html.erb
<style>
  #my-trips {
    width: 90%;
    margin: auto;
  }

  #my-trips th,
  #my-trips td {
    text-align: center;
    padding: 10px;
    border: 1px solid #ccc;
  }

  #my-trips th {
    background-color: #f2f2f2;
  }


  #my-trips tbody tr:nth-child(odd) {
    background-color: #e0e0e0;
  }

  #my-trips tbody tr:nth-child(even) {
    background-color: #f9f9f9;
  }
</style>
<% content_for :body_class, 'body' %>

<h1>Minhas Viagens</h1>

<% if @my_trips.empty? %>
  <p>Você ainda não criou nenhuma viagem, <%= link_to "clique aqui", new_trip_path %> para criar.</p>
<% else %>
  <table id="my-trips">
    <thead>
      <tr>
        <th>Local de Partida</th>
        <th>Local de Chegada</th>
        <th>Data de Partida</th>
        <th>Data de Chegada</th>
        <th>Hora de Partida</th>
        <th>Hora de Chegada</th>
        <th>Tipo de Viagem</th>
        <th>Participantes</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @my_trips.each do |trip| %>
        <tr>
          <td><%= trip.departure_location %></td>
          <td><%= trip.arrival_location %></td>
          <td><%= trip.departure_date.strftime('%d/%m/%Y') %></td>
          <td><%= trip.arrival_date.strftime('%d/%m/%Y') %></td>
          <td><%= trip.departure_time.strftime('%H:%M:%S %Z') %></td>
          <td><%= trip.arrival_time.strftime('%H:%M:%S %Z') %></td>
          <td><%= trip.trip_type %></td>
          <td>
            <% trip.participants.each do |participant| %>
              <%= participant %><br>
            <% end %>
          </td>
          <td>
            <%= link_to "Detalhes", trip, class: "btn btn-primary", style: "margin-bottom: 5px;" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/trips/new.html.erb
<h1>Novo Frete</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Back to trips", trips_path, class: 'btn btn-default btn-gray' %>
</div>

app/views/trips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trip %>

<div>
  <% if current_user && @trip.user.eql?(current_user) %>
    <% if @trip.requested_participants.any? %>
      <%= link_to "Gerenciar solicitações", manage_requests_trip_path(@trip), class: 'btn btn-default'%> 
    <% end %>

    <%= link_to "Editar frete", edit_trip_path(@trip), class: 'btn btn-default'%> 
    <%= link_to "Voltar", trips_path, class: 'btn btn-default'%> 
    <%= form_with(model: @trip, url: trip_path(@trip), method: :delete, data: { confirm: "Are you sure you want to delete this trip?" }) do |form| %>
      <%= form.submit "Excluir frete", class: 'btn btn-default btn-gray', style: 'margin-top: 10px;'%>
    <% end %>
  <% else %>
     <%= link_to "Voltar", trips_path, class: 'btn btn-default'%> 
  <% end %>
</div>