config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :trips do
    get 'join', on: :member

    member do
      patch 'accept_request'
      delete 'reject_request'
      get 'manage_requests'
    end
  end

  delete 'trips/:id', to: 'trips#destroy'
  get 'my_trips', to: 'trips#my_trips'
  
  resources :users
  root to: 'pages#home'
  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'CargoMatch. Todos os direitos reservados.', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', sobre_path %>
      </li>
      <li>
        <%= link_to 'Contato', contato_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<style>
  .navbar {
    background-color: #333333;
    border: none; 
    border-radius: 0; 
  }
</style>

<nav class="navbar navbar-inverse navbar-static-to">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'CargoMatch', root_url, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="expanded-menu">
      <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="inactive">
            <a href=/my_trips>Minhas Viagens</a>
            </li>
          <% end %>

          <li class="inactive">
            <a href=/sobre>Sobre</a>
          </li>
          <li class="inactive">
            <a href=/contato>Contato</a>
          </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Sair', destroy_user_session_path %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Entrar', new_user_registration_path %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CargoMatch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= content_for?(:body_class) ? yield(:body_class) : '' %>">
    <%= render 'layouts/header' %>

    <div class="container">
      <!-- <p class="notice"><%= notice %></p> -->
      <!-- <p class="alert"><%= alert %></p> -->
      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>